/**
 * Palettes.
 *
 * Six roles each, checked as a set: a ground, a surface for cards sitting on
 * it, an accent for rules and ornament, a soft accent for washes, and two text
 * weights. A host never picks a hex code — they pick a name, and the roles are
 * already balanced against each other.
 */

export interface Palette {
  id: string;
  name: string;
  description: string;
  background: string;
  surface: string;
  accent: string;
  accentSoft: string;
  ink: string;
  inkSoft: string;
  /** True when the ground is dark, so scrims and overlays flip. */
  dark?: boolean;
  family: "Warm" | "Cool" | "Earth" | "Jewel" | "Dark" | "Neutral";
}

export const PALETTES: Palette[] = [
  /* ------------------------------------------------------------- warm --- */
  {
    id: "gold-ivory",
    name: "Gold & Ivory",
    description: "Warm, classic and formal. Weddings and ruracio ceremonies.",
    family: "Warm",
    background: "#FBF7F0",
    surface: "#FFFFFF",
    accent: "#B08544",
    accentSoft: "#F5EDDF",
    ink: "#2B241B",
    inkSoft: "#6B6053",
  },
  {
    id: "champagne",
    name: "Champagne",
    description: "Pale gold on oyster. Quietly expensive.",
    family: "Warm",
    background: "#FAF6EF",
    surface: "#FFFFFF",
    accent: "#C9A96A",
    accentSoft: "#F6EEDC",
    ink: "#332C22",
    inkSoft: "#75695A",
  },
  {
    id: "blush",
    name: "Blush",
    description: "Soft rose and cream. Bridal showers and intimate parties.",
    family: "Warm",
    background: "#FDF5F5",
    surface: "#FFFFFF",
    accent: "#B4636F",
    accentSoft: "#F8E6E8",
    ink: "#2E2124",
    inkSoft: "#6E5B5F",
  },
  {
    id: "dusty-rose",
    name: "Dusty rose",
    description: "Muted pink with a grey cast. Modern and restrained.",
    family: "Warm",
    background: "#FAF3F2",
    surface: "#FFFFFF",
    accent: "#A8737A",
    accentSoft: "#F2E2E2",
    ink: "#2C2426",
    inkSoft: "#6C5E60",
  },
  {
    id: "coral",
    name: "Coral",
    description: "Bright and cheerful. Birthdays and daytime parties.",
    family: "Warm",
    background: "#FFF6F2",
    surface: "#FFFFFF",
    accent: "#D9603F",
    accentSoft: "#FCE3D9",
    ink: "#33211B",
    inkSoft: "#7A5B51",
  },
  {
    id: "saffron",
    name: "Saffron",
    description: "Deep yellow-orange on warm white. Celebratory.",
    family: "Warm",
    background: "#FFFAEF",
    surface: "#FFFFFF",
    accent: "#C88A1E",
    accentSoft: "#FBEFD3",
    ink: "#302716",
    inkSoft: "#756748",
  },

  /* ------------------------------------------------------------ earth --- */
  {
    id: "kitenge",
    name: "Kitenge",
    description: "Bold ochre and indigo, drawn from East African print.",
    family: "Earth",
    background: "#FDF6EE",
    surface: "#FFFFFF",
    accent: "#C2571F",
    accentSoft: "#FBE7D6",
    ink: "#25211C",
    inkSoft: "#6B6157",
  },
  {
    id: "terracotta",
    name: "Terracotta",
    description: "Earth reds and clay. Homestead gatherings and harvest meals.",
    family: "Earth",
    background: "#FBF3EE",
    surface: "#FFFFFF",
    accent: "#A8492F",
    accentSoft: "#F7E2D8",
    ink: "#2A1D17",
    inkSoft: "#6E574C",
  },
  {
    id: "sand",
    name: "Sand",
    description: "Warm neutral on neutral. Lets a photograph do the talking.",
    family: "Earth",
    background: "#F7F2E9",
    surface: "#FFFFFF",
    accent: "#8F7F63",
    accentSoft: "#EFE6D6",
    ink: "#2E2A22",
    inkSoft: "#6F675A",
  },
  {
    id: "olive",
    name: "Olive",
    description: "Grey-green and dry. Understated, slightly rustic.",
    family: "Earth",
    background: "#F7F7EF",
    surface: "#FFFFFF",
    accent: "#6B7145",
    accentSoft: "#EAEDDB",
    ink: "#26281D",
    inkSoft: "#666B57",
  },
  {
    id: "clay",
    name: "Clay",
    description: "Soft brick on bone. Homely and grounded.",
    family: "Earth",
    background: "#FAF4F0",
    surface: "#FFFFFF",
    accent: "#9C5D46",
    accentSoft: "#F2E1D8",
    ink: "#2B2019",
    inkSoft: "#6D5C51",
  },
  {
    id: "cocoa",
    name: "Cocoa",
    description: "Deep brown on cream. Rich and old-fashioned.",
    family: "Earth",
    background: "#FAF5EF",
    surface: "#FFFFFF",
    accent: "#5C3D2A",
    accentSoft: "#EDE0D2",
    ink: "#241A13",
    inkSoft: "#65564A",
  },

  /* ------------------------------------------------------------- cool --- */
  {
    id: "botanical",
    name: "Botanical",
    description: "Green and fresh. Garden ceremonies and daytime receptions.",
    family: "Cool",
    background: "#F5F8F3",
    surface: "#FFFFFF",
    accent: "#3F6B4A",
    accentSoft: "#E4EFE5",
    ink: "#1F2A22",
    inkSoft: "#5A6B5E",
  },
  {
    id: "palm",
    name: "Palm & Sand",
    description: "Coastal green on warm sand. Beach and Mombasa celebrations.",
    family: "Cool",
    background: "#FAF7EE",
    surface: "#FFFFFF",
    accent: "#2F6B5F",
    accentSoft: "#DFEDE7",
    ink: "#1D2622",
    inkSoft: "#586A63",
  },
  {
    id: "indigo-brass",
    name: "Indigo & Brass",
    description: "Deep resist-dye blue with brass. Formal and distinctly local.",
    family: "Cool",
    background: "#F4F5F8",
    surface: "#FFFFFF",
    accent: "#23304F",
    accentSoft: "#E5E8F0",
    ink: "#171B26",
    inkSoft: "#565D70",
  },
  {
    id: "slate",
    name: "Slate",
    description: "Understated and modern. Corporate dinners and alumni nights.",
    family: "Cool",
    background: "#F6F7F9",
    surface: "#FFFFFF",
    accent: "#334155",
    accentSoft: "#E4E8EE",
    ink: "#0F172A",
    inkSoft: "#556070",
  },
  {
    id: "seafoam",
    name: "Seafoam",
    description: "Pale aqua and white. Light, airy, coastal.",
    family: "Cool",
    background: "#F1F8F7",
    surface: "#FFFFFF",
    accent: "#3E8580",
    accentSoft: "#DCEEEC",
    ink: "#172624",
    inkSoft: "#4F6764",
  },
  {
    id: "lavender",
    name: "Lavender",
    description: "Soft violet on cool white. Gentle and a little romantic.",
    family: "Cool",
    background: "#F7F5FB",
    surface: "#FFFFFF",
    accent: "#6C5B96",
    accentSoft: "#E8E2F3",
    ink: "#221E2E",
    inkSoft: "#5F5872",
  },
  {
    id: "powder",
    name: "Powder blue",
    description: "Pale blue on white. Christenings, showers, spring.",
    family: "Cool",
    background: "#F3F7FB",
    surface: "#FFFFFF",
    accent: "#41678F",
    accentSoft: "#DEE9F3",
    ink: "#182231",
    inkSoft: "#53637A",
  },

  /* ------------------------------------------------------------ jewel --- */
  {
    id: "emerald",
    name: "Emerald",
    description: "Deep green on ivory. Formal without being severe.",
    family: "Jewel",
    background: "#F6F7F2",
    surface: "#FFFFFF",
    accent: "#1F5741",
    accentSoft: "#DCEAE2",
    ink: "#16221C",
    inkSoft: "#516359",
  },
  {
    id: "burgundy",
    name: "Burgundy",
    description: "Wine red on bone. Evening weddings and winter receptions.",
    family: "Jewel",
    background: "#FAF5F4",
    surface: "#FFFFFF",
    accent: "#7A2233",
    accentSoft: "#F1DEE0",
    ink: "#26171A",
    inkSoft: "#6A5257",
  },
  {
    id: "sapphire",
    name: "Sapphire",
    description: "Strong blue on cool white. Confident and clean.",
    family: "Jewel",
    background: "#F4F6FA",
    surface: "#FFFFFF",
    accent: "#1E4C8A",
    accentSoft: "#DDE7F4",
    ink: "#131B28",
    inkSoft: "#4F5C72",
  },
  {
    id: "aubergine",
    name: "Aubergine",
    description: "Deep purple, nearly black. Dramatic and formal.",
    family: "Jewel",
    background: "#F8F5F8",
    surface: "#FFFFFF",
    accent: "#4A2545",
    accentSoft: "#EBE0EA",
    ink: "#1F1520",
    inkSoft: "#5E4F5D",
  },

  /* ------------------------------------------------------------- dark --- */
  {
    id: "midnight",
    name: "Midnight",
    description: "Dark and formal. Evening receptions, galas and dinners.",
    family: "Dark",
    background: "#12151C",
    surface: "#1B1F29",
    accent: "#C9A227",
    accentSoft: "#2A2A22",
    ink: "#F5F3EF",
    inkSoft: "#A9A8A2",
    dark: true,
  },
  {
    id: "obsidian",
    name: "Obsidian",
    description: "Near-black with a cold silver rule. Severe and modern.",
    family: "Dark",
    background: "#0E0F11",
    surface: "#17191D",
    accent: "#B9C0C9",
    accentSoft: "#23262B",
    ink: "#F2F3F5",
    inkSoft: "#9BA1A9",
    dark: true,
  },
  {
    id: "forest-night",
    name: "Forest night",
    description: "Deep green-black with gold. Garden receptions after dark.",
    family: "Dark",
    background: "#11190F",
    surface: "#1A2418",
    accent: "#C2A44E",
    accentSoft: "#25301F",
    ink: "#F0F3EC",
    inkSoft: "#A3AC9B",
    dark: true,
  },
  {
    id: "ink-navy",
    name: "Ink navy",
    description: "Deep navy with brass. Black tie, without the black.",
    family: "Dark",
    background: "#0F1524",
    surface: "#182033",
    accent: "#C4A059",
    accentSoft: "#232C42",
    ink: "#EFF2F8",
    inkSoft: "#9BA5BA",
    dark: true,
  },
  {
    id: "wine-dark",
    name: "Wine",
    description: "Dark burgundy ground with a rose gold rule.",
    family: "Dark",
    background: "#1A1013",
    surface: "#241619",
    accent: "#C08A79",
    accentSoft: "#2E1E21",
    ink: "#F5EEEC",
    inkSoft: "#B09B97",
    dark: true,
  },

  /* ---------------------------------------------------------- neutral --- */
  {
    id: "ink-white",
    name: "Ink & White",
    description: "Black on white, nothing else. Severe, modern, very quiet.",
    family: "Neutral",
    background: "#FFFFFF",
    surface: "#FAFAFA",
    accent: "#111111",
    accentSoft: "#EFEFEF",
    ink: "#111111",
    inkSoft: "#5B5B5B",
  },
  {
    id: "oyster",
    name: "Oyster",
    description: "Warm grey on warm grey. Almost no contrast, entirely on purpose.",
    family: "Neutral",
    background: "#F4F2EE",
    surface: "#FBFAF8",
    accent: "#7C766C",
    accentSoft: "#E7E3DB",
    ink: "#2A2823",
    inkSoft: "#6C665D",
  },
  {
    id: "graphite",
    name: "Graphite",
    description: "Cool grey with a black rule. Architectural.",
    family: "Neutral",
    background: "#F5F5F6",
    surface: "#FFFFFF",
    accent: "#3A3D42",
    accentSoft: "#E6E7E9",
    ink: "#17181B",
    inkSoft: "#5A5D63",
  },
];

export function paletteById(id: string | null | undefined): Palette {
  return PALETTES.find((palette) => palette.id === id) ?? PALETTES[0]!;
}

export const PALETTE_FAMILIES = [
  "Warm",
  "Earth",
  "Cool",
  "Jewel",
  "Dark",
  "Neutral",
] as const;
